version: '3'
services:
  database:
    image: postgres
    ports:
       - "6543:5432"
    env_file:
      - db.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    
volumes:  
  database-data: